import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import { getDatabase, onValue, ref } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-database.js';

const $=id=>document.getElementById(id); const state={auth:null,db:null,user:null,tournaments:[],matches:[],tasks:[],users:[],notifications:[],announcements:[],adConfig:{}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=m=>{$('toast').textContent=m;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),3000)};
const arr=n=>Object.entries(n||{}).map(([id,v])=>({id,...(v||{})})); const date=v=>v?new Date(v).toLocaleString([], {dateStyle:'medium',timeStyle:'short'}):'—';
async function api(action,payload={}){const token=await state.user.getIdToken(true);const r=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`,'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({action,...payload})});const b=await r.json().catch(()=>({}));if(!r.ok||b.ok===false)throw new Error(b.error||'Request failed');return b}
function showTab(id){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.tabpage').forEach(x=>x.classList.toggle('hidden',x.id!==`tab-${id}`));}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
$('loginBtn').onclick=async()=>{try{await signInWithEmailAndPassword(state.auth,$('email').value.trim(),$('password').value);$('loginMsg').textContent=''}catch(e){$('loginMsg').textContent=e.message.replace('Firebase: ','')}};
$('logout').onclick=()=>signOut(state.auth);
function subscribe(path,cb){onValue(ref(state.db,path),s=>cb(s.val()||{}),e=>{console.error(path,e);toast(`Read failed: ${path}`)})}
function renderStats(){const r=state.tournaments.reduce((n,t)=>n+Number(t.registeredCount||0),0);$('sTournaments').textContent=state.tournaments.length;$('sLive').textContent=state.tournaments.filter(t=>String(t.status||'').toLowerCase()==='live').length;$('sR').textContent=r;$('sMatches').textContent=state.matches.length;$('sUsers').textContent=state.users.length}
function renderTournaments(){ $('tournamentList').innerHTML=state.tournaments.slice().reverse().map(t=>`<div class="listitem"><div class="row"><div><strong>${esc(t.name)}</strong><div class="muted">${esc(t.game)} • ${esc(t.format)} • ${Number(t.registeredCount||0)}/${Number(t.capacity||0)}</div></div><span class="badge ${t.status==='live'?'live':t.status==='completed'?'done':'open'}">${esc(t.status||'open')}</span></div><div class="muted" style="margin-top:7px">Entry ${Number(t.entryFeeCoins||0).toLocaleString()} 🪙 • Prize ${Number(t.prizeCoins||0).toLocaleString()} 🪙 • ${date(t.startAt)}</div><div class="row" style="margin-top:8px"><span class="muted">${esc(t.id)}</span><button class="btn danger" data-close="${esc(t.id)}">Close</button></div></div>`).join('')||'<div class="muted">No tournaments.</div>';document.querySelectorAll('[data-close]').forEach(b=>b.onclick=async()=>{if(!confirm('Close tournament?'))return;try{await api('closeTournament',{tournamentId:b.dataset.close});toast('Tournament closed')}catch(e){toast(e.message)}});$('matchTournament').innerHTML=state.tournaments.map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join('')}
function renderTasks(){ $('taskList').innerHTML=state.tasks.slice().reverse().map(t=>`<div class="listitem"><div class="row"><strong>${esc(t.title)}</strong><span class="badge ${t.active?'open':'done'}">${t.active?'active':'off'}</span></div><div class="muted">${Number(t.rewardCoins||0).toLocaleString()} 🪙 • ${esc(t.type||'task')} ${t.url?`• ${esc(t.url)}`:''}</div><div class="row" style="margin-top:8px"><span class="muted">${esc(t.id)}</span><button class="btn danger" data-del-task="${esc(t.id)}">Delete</button></div></div>`).join('')||'<div class="muted">No tasks.</div>';document.querySelectorAll('[data-del-task]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete task?'))return;try{await api('deleteTask',{taskId:b.dataset.delTask});toast('Task deleted')}catch(e){toast(e.message)}})}
function renderUsers(){ $('userList').innerHTML=state.users.slice(0,80).map(u=>`<div class="listitem"><div class="row"><div><strong>${esc(u.displayName||'Player')}</strong><div class="muted">${esc(u.uid||u.id)} • ${esc(u.game||'Other')} • ${esc(u.gameId||'No game ID')}</div></div><span class="badge">${esc(u.status||'active')}</span></div></div>`).join('')||'<div class="muted">No profiles yet.</div>' }
function renderMatches(){ $('matchList').innerHTML=state.matches.slice().reverse().slice(0,80).map(m=>`<div class="listitem"><div class="row"><strong>${esc(m.tournamentName||'Match')}</strong><span class="badge done">${esc(m.status||'completed')}</span></div><div>${esc(m.player1)} ${Number(m.score1||0)} — ${Number(m.score2||0)} ${esc(m.player2)}</div><div class="muted">${esc(m.round||'Match')} • ${date(m.updatedAt)}</div></div>`).join('')||'<div class="muted">No matches.</div>' }
function renderAnnouncements(){const items=[...state.announcements,...state.notifications].sort((a,b)=>Number(b.createdAt||0)-Number(a.createdAt||0));$('contentList').innerHTML=items.slice(0,60).map(x=>`<div class="listitem"><strong>${esc(x.title)}</strong><div class="muted">${esc(x.body)}</div></div>`).join('')||'<div class="muted">No messages.</div>'}
function renderAds(){const p=state.adConfig?.providers||[];$('adsJson').value=JSON.stringify(p,null,2);$('adsEnabled').checked=state.adConfig?.enabled!==false}
function bind(){
 $('createBtn').onclick=async()=>{try{const start=$('start').value?new Date($('start').value).toISOString():new Date(Date.now()+86400000).toISOString();const end=$('end').value?new Date($('end').value).toISOString():new Date(Date.now()+172800000).toISOString();await api('createTournament',{name:$('name').value,game:$('game').value,mode:$('mode').value,format:$('format').value,capacity:Number($('capacity').value||32),entryFeeCoins:Number($('entry').value||0),prizeCoins:Number($('prize').value||0),startAt:start,endAt:end,registrationDeadline:start,description:$('description').value,rules:$('rules').value});toast('Tournament published');$('name').value='';$('description').value='';$('rules').value=''}catch(e){toast(e.message)}};
 $('saveTask').onclick=async()=>{try{await api('createTask',{title:$('taskTitle').value,description:$('taskDescription').value,type:$('taskType').value,url:$('taskUrl').value,rewardCoins:Number($('taskReward').value||0),active:$('taskActive').checked});toast('Task published');['taskTitle','taskDescription','taskUrl','taskReward'].forEach(id=>$(id).value='')}catch(e){toast(e.message)}};
 $('saveMatch').onclick=async()=>{try{await api('saveMatch',{tournamentId:$('matchTournament').value,matchId:$('matchId').value,player1:$('p1').value,player2:$('p2').value,score1:Number($('score1').value||0),score2:Number($('score2').value||0),round:$('round').value,points:Number($('points').value||3)});toast('Match result saved')}catch(e){toast(e.message)}};
 $('adjustCoins').onclick=async()=>{try{await api('adjustCoins',{uid:$('coinUid').value.trim(),amount:Number($('coinAmount').value),reason:$('coinReason').value});toast('Wallet updated')}catch(e){toast(e.message)}};
 $('publishAnnouncement').onclick=async()=>{try{await api('publishAnnouncement',{title:$('aTitle').value,body:$('aBody').value});toast('Announcement published');$('aTitle').value='';$('aBody').value=''}catch(e){toast(e.message)}};
 $('publishNotification').onclick=async()=>{try{await api('publishNotification',{title:$('nTitle').value,body:$('nBody').value});toast('Notification published');$('nTitle').value='';$('nBody').value=''}catch(e){toast(e.message)}};
 $('saveAds').onclick=async()=>{try{let providers=JSON.parse($('adsJson').value||'[]');if(!Array.isArray(providers))throw new Error('Providers must be a JSON array');await api('saveAdConfig',{enabled:$('adsEnabled').checked,providers});toast('Ad configuration saved')}catch(e){toast(e.message)}};
}
async function enterAdmin(){try{const r=await api('getAdminStats');$('login').classList.add('hidden');$('app').classList.remove('hidden');$('adminUid').textContent=state.user.uid;Object.entries(r.stats||{}).forEach(([k,v])=>{const el=$(`s${k[0].toUpperCase()}${k.slice(1)}`);if(el)el.textContent=v});subscribe('tournaments',v=>{state.tournaments=arr(v);renderTournaments();renderStats()});subscribe('matches',v=>{state.matches=arr(v);renderMatches();renderStats()});subscribe('tasks',v=>{state.tasks=arr(v);renderTasks()});subscribe('users',v=>{state.users=arr(v);renderUsers();renderStats()});subscribe('announcements',v=>{state.announcements=arr(v);renderAnnouncements()});subscribe('notifications',v=>{state.notifications=arr(v);renderAnnouncements()});subscribe('adConfig',v=>{state.adConfig=v||{};renderAds()});bind();renderStats()}catch(e){await signOut(state.auth);$('loginMsg').textContent=e.message}}
async function boot(){try{const r=await fetch('/api/firebase-config',{cache:'no-store'});const cfg=await r.json();if(!r.ok)throw new Error(cfg.error||'Firebase unavailable');const app=initializeApp(cfg);state.auth=getAuth(app);state.db=getDatabase(app);onAuthStateChanged(state.auth,u=>{state.user=u;if(u)enterAdmin()});}catch(e){$('loginMsg').textContent=e.message}}
boot();
