import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import { initializeAppCheck, ReCaptchaEnterpriseProvider, getToken as getAppCheckToken } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app-check.js';
import { getAuth, onAuthStateChanged, signInAnonymously } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import { getDatabase, onValue, ref } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-database.js';

const $ = id => document.getElementById(id);
const state = { db:null, auth:null, appCheck:null, user:null, tournaments:[], matches:[], leaderboard:[], tasks:[], notifications:[], announcements:[], account:{}, profile:{}, adConfig:{}, filter:'all', search:'', unsub:[] };
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast = message => { $('toast').textContent = message; $('toast').classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => $('toast').classList.remove('show'), 3200); };
const busy = value => $('loader').classList.toggle('show', value);
const money = value => Number(value || 0).toLocaleString('en-IN');
const date = value => value ? new Date(value).toLocaleString([], {dateStyle:'medium',timeStyle:'short'}) : '—';
const status = t => { const forced=String(t.status||'').toLowerCase(); if(forced==='completed'||forced==='closed') return 'completed'; if(forced==='live') return 'live'; const s=Date.parse(t.startAt||''); const e=Date.parse(t.endAt||''); const n=Date.now(); if(s&&n<s) return 'upcoming'; if(s&&e&&n<=e) return 'live'; return 'open'; };
const arr = node => Object.entries(node || {}).map(([id,value]) => ({id,...(value || {})}));

function go(id){ document.querySelectorAll('.section').forEach(x=>x.classList.add('hidden')); $(id)?.classList.remove('hidden'); document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===id)); if(id==='tournaments') renderTournaments(); if(id==='matches') renderMatches(); if(id==='leaderboard') renderLeaderboard(); if(id==='wallet') renderWallet(); if(id==='tasks') renderTasks(); if(id==='notifications') renderNotifications(); if(id==='profile') renderProfile(); if(id==='home') renderHome(); window.scrollTo({top:0,behavior:'smooth'}); }
document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
$('browseBtn').onclick=()=>go('tournaments'); $('closeModal').onclick=()=> $('modal').classList.remove('show'); $('refreshBtn').onclick=()=>location.reload(); $('search').oninput=e=>{state.search=e.target.value.toLowerCase();renderTournaments()}; $('notifyBtn').onclick=()=>go('notifications'); $('profileBtn').onclick=()=>go('profile');
document.querySelectorAll('#filters .chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('#filters .chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;renderTournaments()});

async function api(action,payload={}){
  if(!state.user) throw new Error('Please wait for account connection');
  const token=await state.user.getIdToken(true); const headers={'Content-Type':'application/json','Authorization':`Bearer ${token}`,'Idempotency-Key':crypto.randomUUID()};
  if(state.appCheck){ try{const tokenResult=await getAppCheckToken(state.appCheck,false); if(tokenResult.token) headers['X-Firebase-AppCheck']=tokenResult.token;}catch(e){ if(window.__appCheckRequired) throw new Error('App Check verification failed'); } }
  const response=await fetch('/api/command',{method:'POST',headers,body:JSON.stringify({action,...payload})});
  let body={}; try{body=await response.json()}catch{}
  if(!response.ok||body.ok===false) throw new Error(body.error||'Request failed');
  return body;
}

function subscribe(path,callback){const stop=onValue(ref(state.db,path),snap=>callback(snap.val()||{}),error=>{console.error(path,error);toast(`Live data error: ${path}`)});state.unsub.push(stop)}
function subscribeAll(){state.unsub.forEach(stop=>stop());state.unsub=[]; subscribe('tournaments',v=>{state.tournaments=arr(v);renderTournaments();renderHome()}); subscribe(`matchesByUser/${state.user.uid}`,v=>{const all=arr(v);state.matches=all.filter(x=>x.id!=='pending').sort((a,b)=>Number(b.updatedAt||0)-Number(a.updatedAt||0));renderMatches();renderHome()}); subscribe('leaderboard',v=>{state.leaderboard=arr(v).sort((a,b)=>Number(b.points||0)-Number(a.points||0));renderLeaderboard();renderHome()}); subscribe('tasks',v=>{state.tasks=arr(v).filter(x=>x.active!==false);renderTasks()}); subscribe('notifications',v=>{state.notifications=arr(v).sort((a,b)=>Number(b.createdAt||0)-Number(a.createdAt||0));renderNotifications()}); subscribe('announcements',v=>{state.announcements=arr(v).sort((a,b)=>Number(b.createdAt||0)-Number(a.createdAt||0));renderNotifications()}); subscribe(`accounts/${state.user.uid}`,v=>{state.account=v||{};renderWallet();renderHome()}); subscribe(`users/${state.user.uid}`,v=>{state.profile=v||{};renderProfile()}); subscribe('adConfig',v=>{state.adConfig=v||{};renderAds()}); }

function renderHome(){ $('statT').textContent=state.tournaments.length; $('statLive').textContent=state.tournaments.filter(t=>status(t)==='live').length; $('statM').textContent=state.matches.length; $('statP').textContent=state.leaderboard.length; $('balance').textContent=money(state.account.balance); const top=state.tournaments.filter(t=>status(t)!=='completed').slice(0,3); $('homeTournaments').innerHTML=top.map(tournamentCard).join('')||'<div class="empty">No tournaments published yet.</div>'; renderAds(); }
function tournamentCard(t){const s=status(t),registered=Number(t.registeredCount||0),cap=Number(t.capacity||0),pct=cap?Math.min(100,registered/cap*100):0;return `<article class="card"><div class="banner"><span class="tag">${esc(s.toUpperCase())}</span><div><div class="eyebrow">${esc(t.game||'Esports')}</div><h3>${esc(t.name||'Tournament')}</h3></div></div><div class="cardbody"><div class="muted">${esc(t.format||'Tournament')} • ${esc(t.mode||'Open')}</div><div class="meta"><div><small>Entry</small><strong>${money(t.entryFeeCoins||0)} 🪙</strong></div><div><small>Prize</small><strong>${money(t.prizeCoins||0)} 🪙</strong></div><div><small>Players</small><strong>${registered}${cap?`/${cap}`:''}</strong></div></div><div class="muted" style="font-size:12px">Starts ${date(t.startAt)}</div><div class="progress"><i style="width:${pct}%"></i></div><div class="row"><span class="badge ${s==='live'?'live':s==='completed'?'done':'open'}">${esc(s)}</span><button class="btn primary" data-join="${esc(t.id)}">${s==='completed'?'Closed':'Open'}</button></div></div></article>`}
function renderTournaments(){const q=state.search;let list=state.tournaments.filter(t=>state.filter==='all'||status(t)===state.filter);if(q) list=list.filter(t=>`${t.name} ${t.game} ${t.id} ${t.format}`.toLowerCase().includes(q)); $('tournamentGrid').innerHTML=list.map(tournamentCard).join('')||'<div class="empty">No tournaments match your filters.</div>';document.querySelectorAll('[data-join]').forEach(b=>b.onclick=()=>openTournament(b.dataset.join));}
function openTournament(id){const t=state.tournaments.find(x=>x.id===id);if(!t)return;const s=status(t);$('modalTitle').textContent=t.name||'Tournament';$('modalBody').innerHTML=`<div class="stack"><div class="notice">${esc(t.description||'Official tournament hosted on Podmen X.')}</div><div class="meta"><div><small>Game</small><strong>${esc(t.game||'—')}</strong></div><div><small>Entry</small><strong>${money(t.entryFeeCoins||0)} 🪙</strong></div><div><small>Prize</small><strong>${money(t.prizeCoins||0)} 🪙</strong></div></div><p class="muted">${esc(t.rules||'Rules will be published by the admin.')}</p><p class="muted">Registration closes ${date(t.registrationDeadline)}.</p><div class="form"><input class="field" id="joinGameId" placeholder="Your game / player ID" value="${esc(state.profile.gameId||'')}"><button class="btn primary" id="joinConfirm" ${s==='completed'?'disabled':''}>Join with ${money(t.entryFeeCoins||0)} coins</button></div></div>`;$('modal').classList.add('show');$('joinConfirm').onclick=async()=>{try{busy(true);const result=await api('joinTournament',{tournamentId:id,displayName:state.profile.displayName||'Player',gameId:$('joinGameId').value.trim()});$('modal').classList.remove('show');toast(result.alreadyJoined?'You are already registered.':`Joined successfully. ${money(result.fee||0)} coins deducted.`)}catch(e){toast(e.message)}finally{busy(false)}};}
function renderMatches(){const list=state.matches; $('matchesList').innerHTML=list.map(m=>`<div class="card"><div class="cardbody"><div class="row"><strong>${esc(m.tournamentName||'Match')}</strong><span class="badge ${m.status==='completed'?'done':'live'}">${esc(m.status||'match')}</span></div><div style="margin-top:10px">${esc(m.player1||'Player 1')} <strong>${esc(m.score1??0)}</strong> — <strong>${esc(m.score2??0)}</strong> ${esc(m.player2||'Player 2')}</div><div class="muted" style="margin-top:6px">${esc(m.round||'Match')} • ${date(m.updatedAt)}</div></div></div>`).join('')||'<div class="empty">No matches assigned yet.</div>';}
function renderLeaderboard(){const list=state.leaderboard.slice(0,100);$('leaderboardList').innerHTML=list.map((p,i)=>`<div class="listitem"><div class="row"><div><strong>#${i+1} ${esc(p.displayName||p.id||'Player')}</strong><div class="muted">${esc(p.game||'Esports')}</div></div><strong>${money(p.points||0)} pts</strong></div></div>`).join('')||'<div class="empty">Leaderboard will appear after official results.</div>';}
function renderWallet(){const ledger=Object.entries(state.account.ledger||{}).map(([id,x])=>({id,...x})).sort((a,b)=>Number(b.createdAt||0)-Number(a.createdAt||0)).slice(0,40);$('balance').textContent=money(state.account.balance);$('walletList').innerHTML=ledger.map(x=>`<div class="listitem"><div class="row"><strong>${esc(x.description||x.type||'Transaction')}</strong><strong class="${Number(x.amount||0)>=0?'success-text':'danger-text'}">${Number(x.amount||0)>=0?'+':''}${money(x.amount||0)} 🪙</strong></div><div class="muted">Balance ${money(x.balanceAfter||0)} • ${date(x.createdAt)}</div></div>`).join('')||'<div class="empty">No wallet transactions yet.</div>';}
function renderTasks(){const claimed=state.account.claimedTasks||{};$('tasksList').innerHTML=state.tasks.map(t=>{const done=!!claimed[t.id];return `<div class="card"><div class="cardbody"><div class="row"><strong>${esc(t.title||'Task')}</strong><span class="badge open">+${money(t.rewardCoins||0)} 🪙</span></div><p class="muted">${esc(t.description||'Complete this task and claim the reward.')}</p>${t.url?`<a class="btn" href="${esc(t.url)}" target="_blank" rel="noopener noreferrer">Open task</a>`:''}<button class="btn primary" data-task="${esc(t.id)}" ${done?'disabled':''}>${done?'Claimed':'Claim reward'}</button></div></div>`}).join('')||'<div class="empty">No active tasks right now.</div>';document.querySelectorAll('[data-task]').forEach(b=>b.onclick=async()=>{try{busy(true);const r=await api('claimTask',{taskId:b.dataset.task});toast(`Task complete. +${money(r.reward)} coins.`)}catch(e){toast(e.message)}finally{busy(false)}});}
function renderNotifications(){const items=[...state.notifications.map(x=>({...x,_type:'Notification'})),...state.announcements.map(x=>({...x,_type:'Announcement'}))].sort((a,b)=>Number(b.createdAt||0)-Number(a.createdAt||0)).slice(0,80);$('notificationsList').innerHTML=items.map(x=>`<div class="listitem"><div class="row"><strong>${esc(x.title||x._type)}</strong><span class="badge">${esc(x._type)}</span></div><p class="muted">${esc(x.body||'')}</p><div class="muted">${date(x.createdAt)}</div></div>`).join('')||'<div class="empty">No notifications yet.</div>';}
function renderProfile(){const p=state.profile||{};$('playerName').textContent=p.displayName||'Player';$('playerId').textContent=state.user?.uid||'Connecting';$('displayName').value=p.displayName||'';$('gameId').value=p.gameId||'';$('game').value=p.game||'Other';}
$('saveProfile').onclick=async()=>{try{busy(true);await api('updateProfile',{displayName:$('displayName').value,gameId:$('gameId').value,game:$('game').value});toast('Profile saved')}catch(e){toast(e.message)}finally{busy(false)}};
function renderAds(){const root=$('adslot');if(!root)return;const cfg=state.adConfig;if(!cfg?.enabled||!Array.isArray(cfg.providers)){root.innerHTML='';return;} const p=cfg.providers.find(x=>x.enabled&&x.network==='adsense'&&x.clientId&&x.slotId);if(!p){root.innerHTML='';return;} root.innerHTML=`<ins class="adsbygoogle" style="display:block" data-ad-client="${esc(p.clientId)}" data-ad-slot="${esc(p.slotId)}" data-ad-format="auto" data-full-width-responsive="true"></ins>`;const s=document.createElement('script');s.async=true;s.src='https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client='+encodeURIComponent(p.clientId);s.crossOrigin='anonymous';s.onload=()=>{try{(window.adsbygoogle=window.adsbygoogle||[]).push({})}catch(e){console.error(e)}};document.head.appendChild(s);}

async function boot(){try{const cfgResponse=await fetch('/api/firebase-config',{cache:'no-store'});const cfg=await cfgResponse.json();if(!cfgResponse.ok)throw new Error(cfg.error||'Firebase configuration unavailable');window.__appCheckRequired=cfg.appCheckEnabled===true;const app=initializeApp(cfg);if(cfg.appCheckEnabled&&cfg.recaptchaSiteKey){try{state.appCheck=initializeAppCheck(app,{provider:new ReCaptchaEnterpriseProvider(cfg.recaptchaSiteKey),isTokenAutoRefreshEnabled:true})}catch(e){console.error('App Check init',e)}}state.auth=getAuth(app);state.db=getDatabase(app);onAuthStateChanged(state.auth,user=>{state.user=user;if(!user){$('connection').textContent='Signing in…';return;}$('connection').textContent='● Live';$('playerId').textContent=user.uid;subscribeAll();renderHome()});await signInAnonymously(state.auth)}catch(e){console.error(e);$('connection').textContent='Backend unavailable';toast(e.message||'Unable to connect to Firebase')}}

go('home');boot();
